/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-tint': '#3e5e95',
        'on-surface': '#0b1c30',
        'on-secondary-fixed-variant': '#004f4f',
        'surface-container-high': '#dce9ff',
        'border-subtle': '#E2E8F0',
        surface: '#f8f9ff',
        tertiary: '#330e00',
        'tertiary-fixed-dim': '#ffb597',
        'primary-fixed': '#d7e2ff',
        'on-background': '#0b1c30',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#360f00',
        'on-primary-fixed-variant': '#24467c',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#002020',
        'on-surface-variant': '#43474f',
        'surface-container-highest': '#d3e4fe',
        'primary-container': '#002d62',
        'on-secondary-container': '#006e6e',
        'on-tertiary': '#ffffff',
        primary: '#00193c',
        'on-tertiary-container': '#d4815d',
        'tertiary-fixed': '#ffdbcd',
        'surface-bright': '#f8f9ff',
        'surface-bg': '#F8FAFC',
        'data-growth': '#10B981',
        'on-error': '#ffffff',
        'tertiary-container': '#541d02',
        secondary: '#006a6a',
        'inverse-on-surface': '#eaf1ff',
        'surface-variant': '#d3e4fe',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#743417',
        'outline-variant': '#c4c6d1',
        outline: '#747781',
        'secondary-fixed': '#93f2f2',
        'primary-fixed-dim': '#abc7ff',
        'secondary-fixed-dim': '#76d6d5',
        'on-primary-container': '#7796d1',
        'on-primary-fixed': '#001b3f',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-container-lowest': '#ffffff',
        background: '#f8f9ff',
        'ink-dark': '#0F172A',
        'inverse-primary': '#abc7ff',
        'inverse-surface': '#213145',
        'secondary-container': '#90efef',
        'surface-dim': '#cbdbf5',
        'surface-container-low': '#eff4ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '80px',
        'margin-desktop': '40px',
        'stack-sm': '8px',
        'container-max': '1200px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg': ['"Playfair Display"', 'serif'],
        'label-caps': ['"Source Sans 3"', 'sans-serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-display': ['"Playfair Display"', 'serif'],
        'body-lg': ['"Source Sans 3"', 'sans-serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'body-md': ['"Source Sans 3"', 'sans-serif'],
        'label-sm': ['"Source Sans 3"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
